name: UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-ui-tests:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest with Selenium
        env:
          SELENIUM_URL: http://localhost:4444/wd/hub
        run: pytest --driver Remote --capability browserName chrome --selenium-url $SELENIUM_URL

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: reports/*.xml

      - name: Upload test screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: selenium-screenshots
          path: screenshots/
